### PR TITLE
Update examples source code

### PR DESCRIPTION
**Pull request by Evegen55**
There are lots of good examples how we can use Unfolding but have been written for Processing 2.2.1. Since version 3 the Processing language not support Applet and has another way for create main application. In this fork we can use all examples with last version of the Processing libraries for Java. All examples work correctly.

### CODE REVIEW

**Comment by tillnagel** [comment]
Thanks so much for your efforts!

However, for me to merge please do not use your own code style. Also, please do not change the modifiers. And lastly, uppercase variable names should be used for final variables only.

**Comment by Evegen55** [comment]
Thanks a lot for notes! ok, may be I'll to do it in another branch and maybe it will take couple of days. But what would you tell about two serios fixes - commit "TODO Move addUniqueMarkers to UnfoldingMap. - resolved" and "fix bug with MarkerFactory"? Also about commit "add javaDoc task for examples, add note for HelloWorld"? Should I immplement it in another branch?

**Comment by tillnagel** [comment]
Let me try and cherry pick those commits, on the weekend. I'll come back to you if I face issues regarding this.

**Comment by Evegen55** [comment]
ok, thanks!

**Comment by Evegen55** [comment]
I have another question - what about @override annotation? May be I could try to paste in appropriate places?

**Pull request closed without merging**
